package com.margai.curriculum.internal;

import com.margai.curriculum.api.BookLanguage;
import com.margai.curriculum.api.NcertParagraphRow;
import com.margai.curriculum.api.ParagraphExtraction;
import com.margai.curriculum.api.ParagraphVerification;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

/**
 * {@code ncert_paragraphs} (TECH_PLAN §2.3, migration V7): the paragraph-level NCERT layer that
 * every grounded answer anchors to (SPEC §9 item 2, §6.3). One row per address, both languages
 * on it, so an EN and a HI edition of the same paragraph never become two rows.
 *
 * <p>Two columns are deliberately unmapped: {@code tsv} is generated by the database, and
 * {@code embedding} arrives at D17 with {@code ncert embed} and its HNSW index (§2.9).
 * {@code nodeId} is set by the D23 anchor pass, so the loader never touches it.
 */
@Entity
@Table(name = "ncert_paragraphs")
public class NcertParagraph {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, updatable = false)
    private UUID bookId;

    @Column(nullable = false)
    private short chapterNo;

    @Column(nullable = false, length = 16)
    private String section;

    @Column(nullable = false)
    private short paraNo;

    private UUID nodeId;

    private String textEn;

    private String textHi;

    @JdbcTypeCode(SqlTypes.JSON)
    private List<String> figureRefs;

    @Column(nullable = false)
    private boolean hasEquations;

    /**
     * Provenance per edition, {@code {"en": {…}, "hi": {…}}}. Keyed by language because the two
     * editions are read from different page images by different calls: a single object let D16's
     * Hindi pass erase the English text's pages, confidence and {@code ai_call_id}, against the
     * traceability {@link ParagraphExtraction} promises (spec-auditor, D14).
     */
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<BookLanguage, ParagraphExtraction> extraction = new EnumMap<>(BookLanguage.class);

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    protected NcertParagraph() {
        // JPA
    }

    public NcertParagraph(UUID bookId, NcertParagraphRow row, BookLanguage language) {
        this.bookId = bookId;
        this.chapterNo = row.chapterNo();
        this.section = row.section();
        this.paraNo = row.paraNo();
        apply(row, language);
    }

    /**
     * {@code ncert load}'s upsert on the paragraph address (TECH_PLAN §6.3). The text lands in
     * the column of the edition being loaded, so loading Hindi at D16 leaves the English text
     * standing. Returns whether anything changed.
     */
    /**
     * The edition being loaded supplies the text, its own provenance, and the paragraph's figure
     * references and equation flag.
     *
     * <p>Those last two are <em>replaced</em>, not merged. Merging them across loads looked kinder
     * — the two editions print the same figures — but it made the load non-idempotent within one
     * edition: a re-extraction correcting a hallucinated {@code Fig. 7.9} could never clear it, and
     * because {@code changed} compared against the merged value the report called the row
     * unchanged while discarding the correction (spec-auditor, D14). `--redo` then `load` is the
     * founder's only remedy for a bad page, so the current JSONL has to win outright.
     */
    public boolean apply(NcertParagraphRow row, BookLanguage language) {
        // The second read's verdict is about the words (D15): a load that brings the same text
        // keeps it, so reloading a frozen run never costs a re-verification; a load that changes
        // the text — a correction, a re-extraction — drops it, because it judged other words.
        ParagraphExtraction incoming = row.extraction();
        ParagraphExtraction current = extraction.get(language);
        if (incoming != null && incoming.verification() == null && current != null
                && current.verification() != null && Objects.equals(text(language), row.text())) {
            incoming = incoming.withVerification(current.verification());
        }
        boolean changed = !Objects.equals(text(language), row.text())
                || hasEquations != row.hasEquations()
                || !Objects.equals(figureRefs, row.figureRefs())
                || !Objects.equals(current, incoming);
        if (changed) {
            if (language == BookLanguage.en) {
                this.textEn = row.text();
            } else {
                this.textHi = row.text();
            }
            this.hasEquations = row.hasEquations();
            this.figureRefs = row.figureRefs();
            Map<BookLanguage, ParagraphExtraction> updated = new EnumMap<>(extraction);
            updated.put(language, incoming);
            this.extraction = updated;
        }
        return changed;
    }

    /**
     * {@code ncert verify --read-pages} (D15): the verdict onto this edition's provenance. The
     * caller has already checked that it names this row's current text.
     */
    public void recordVerification(BookLanguage language, ParagraphVerification verification) {
        Map<BookLanguage, ParagraphExtraction> updated = new EnumMap<>(extraction);
        updated.put(language, extraction.get(language).withVerification(verification));
        this.extraction = updated;
    }

    /** This row as one edition's paragraph, the shape the pipeline loaded and reads back. */
    public NcertParagraphRow row(BookLanguage language) {
        return new NcertParagraphRow(chapterNo, section, paraNo, text(language), hasEquations, figureRefs,
                extraction.get(language));
    }

    public String text(BookLanguage language) {
        return language == BookLanguage.en ? textEn : textHi;
    }

    /** The address the founder spot-checks against the PDF (PLAN D14 ✅). */
    public String address() {
        return "ch " + chapterNo + " §" + section + " ¶" + paraNo;
    }

    public UUID getId() {
        return id;
    }

    public UUID getBookId() {
        return bookId;
    }

    public short getChapterNo() {
        return chapterNo;
    }

    public String getSection() {
        return section;
    }

    public short getParaNo() {
        return paraNo;
    }

    public UUID getNodeId() {
        return nodeId;
    }

    public String getTextEn() {
        return textEn;
    }

    public String getTextHi() {
        return textHi;
    }

    public List<String> getFigureRefs() {
        return figureRefs;
    }

    public boolean isHasEquations() {
        return hasEquations;
    }

    /** How this edition's text was read; null when that edition has not been loaded. */
    public ParagraphExtraction getExtraction(BookLanguage language) {
        return extraction.get(language);
    }

    public Map<BookLanguage, ParagraphExtraction> getExtraction() {
        return Map.copyOf(extraction);
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
