package com.margai.curriculum.internal;

import com.margai.curriculum.api.BookLanguage;
import com.margai.curriculum.api.NcertParagraphRow;
import com.margai.curriculum.api.ParagraphExtraction;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

/**
 * {@code ncert_paragraphs} (TECH_PLAN §2.3, migration V7): the paragraph-level NCERT layer that
 * every grounded answer anchors to (SPEC §9 item 2, §6.3). One row per address, both languages
 * on it, so an EN and a HI edition of the same paragraph never become two rows.
 *
 * <p>Two columns are deliberately unmapped: {@code tsv} is generated by the database, and
 * {@code embedding} arrives at D17 with {@code ncert embed} and its HNSW index (§2.9).
 * {@code nodeId} is set by the D23 anchor pass, so the loader never touches it.
 */
@Entity
@Table(name = "ncert_paragraphs")
public class NcertParagraph {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, updatable = false)
    private UUID bookId;

    @Column(nullable = false)
    private short chapterNo;

    @Column(nullable = false, length = 16)
    private String section;

    @Column(nullable = false)
    private short paraNo;

    private UUID nodeId;

    private String textEn;

    private String textHi;

    @JdbcTypeCode(SqlTypes.JSON)
    private List<String> figureRefs;

    @Column(nullable = false)
    private boolean hasEquations;

    @JdbcTypeCode(SqlTypes.JSON)
    private ParagraphExtraction extraction;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    protected NcertParagraph() {
        // JPA
    }

    public NcertParagraph(UUID bookId, NcertParagraphRow row, BookLanguage language) {
        this.bookId = bookId;
        this.chapterNo = row.chapterNo();
        this.section = row.section();
        this.paraNo = row.paraNo();
        apply(row, language);
    }

    /**
     * {@code ncert load}'s upsert on the paragraph address (TECH_PLAN §6.3). The text lands in
     * the column of the edition being loaded, so loading Hindi at D16 leaves the English text
     * standing. Returns whether anything changed.
     */
    public boolean apply(NcertParagraphRow row, BookLanguage language) {
        boolean changed = !Objects.equals(text(language), row.text())
                || hasEquations != row.hasEquations()
                || !Objects.equals(figureRefs, row.figureRefs())
                || !Objects.equals(extraction, row.extraction());
        if (changed) {
            if (language == BookLanguage.en) {
                this.textEn = row.text();
            } else {
                this.textHi = row.text();
            }
            this.hasEquations = row.hasEquations();
            this.figureRefs = row.figureRefs();
            this.extraction = row.extraction();
        }
        return changed;
    }

    public String text(BookLanguage language) {
        return language == BookLanguage.en ? textEn : textHi;
    }

    /** The address the founder spot-checks against the PDF (PLAN D14 ✅). */
    public String address() {
        return "ch " + chapterNo + " §" + section + " ¶" + paraNo;
    }

    public UUID getId() {
        return id;
    }

    public UUID getBookId() {
        return bookId;
    }

    public short getChapterNo() {
        return chapterNo;
    }

    public String getSection() {
        return section;
    }

    public short getParaNo() {
        return paraNo;
    }

    public UUID getNodeId() {
        return nodeId;
    }

    public String getTextEn() {
        return textEn;
    }

    public String getTextHi() {
        return textHi;
    }

    public List<String> getFigureRefs() {
        return figureRefs;
    }

    public boolean isHasEquations() {
        return hasEquations;
    }

    public ParagraphExtraction getExtraction() {
        return extraction;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
