package com.margai.curriculum.internal;

import com.margai.curriculum.api.BookLanguage;
import com.margai.curriculum.api.NcertParagraphRow;
import com.margai.curriculum.api.ParagraphExtraction;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

/**
 * {@code ncert_paragraphs} (TECH_PLAN §2.3, migration V7): the paragraph-level NCERT layer that
 * every grounded answer anchors to (SPEC §9 item 2, §6.3). One row per address, both languages
 * on it, so an EN and a HI edition of the same paragraph never become two rows.
 *
 * <p>Two columns are deliberately unmapped: {@code tsv} is generated by the database, and
 * {@code embedding} arrives at D17 with {@code ncert embed} and its HNSW index (§2.9).
 * {@code nodeId} is set by the D23 anchor pass, so the loader never touches it.
 */
@Entity
@Table(name = "ncert_paragraphs")
public class NcertParagraph {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false, updatable = false)
    private UUID bookId;

    @Column(nullable = false)
    private short chapterNo;

    @Column(nullable = false, length = 16)
    private String section;

    @Column(nullable = false)
    private short paraNo;

    private UUID nodeId;

    private String textEn;

    private String textHi;

    @JdbcTypeCode(SqlTypes.JSON)
    private List<String> figureRefs;

    @Column(nullable = false)
    private boolean hasEquations;

    /**
     * Provenance per edition, {@code {"en": {…}, "hi": {…}}}. Keyed by language because the two
     * editions are read from different page images by different calls: a single object let D16's
     * Hindi pass erase the English text's pages, confidence and {@code ai_call_id}, against the
     * traceability {@link ParagraphExtraction} promises (spec-auditor, D14).
     */
    @JdbcTypeCode(SqlTypes.JSON)
    private Map<BookLanguage, ParagraphExtraction> extraction = new EnumMap<>(BookLanguage.class);

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    protected NcertParagraph() {
        // JPA
    }

    public NcertParagraph(UUID bookId, NcertParagraphRow row, BookLanguage language) {
        this.bookId = bookId;
        this.chapterNo = row.chapterNo();
        this.section = row.section();
        this.paraNo = row.paraNo();
        apply(row, language);
    }

    /**
     * {@code ncert load}'s upsert on the paragraph address (TECH_PLAN §6.3). The text lands in
     * the column of the edition being loaded, so loading Hindi at D16 leaves the English text
     * standing. Returns whether anything changed.
     */
    public boolean apply(NcertParagraphRow row, BookLanguage language) {
        List<String> mergedRefs = mergeFigureRefs(row.figureRefs());
        boolean mergedEquations = hasEquations || row.hasEquations();
        boolean changed = !Objects.equals(text(language), row.text())
                || hasEquations != mergedEquations
                || !Objects.equals(figureRefs, mergedRefs)
                || !Objects.equals(extraction.get(language), row.extraction());
        if (changed) {
            if (language == BookLanguage.en) {
                this.textEn = row.text();
            } else {
                this.textHi = row.text();
            }
            // Both editions print the same paragraph, so these describe it rather than one reading
            // of it: union the figures and keep an equation seen in either, instead of letting the
            // second edition loaded erase what the first found.
            this.hasEquations = mergedEquations;
            this.figureRefs = mergedRefs;
            Map<BookLanguage, ParagraphExtraction> updated = new EnumMap<>(extraction);
            updated.put(language, row.extraction());
            this.extraction = updated;
        }
        return changed;
    }

    private List<String> mergeFigureRefs(List<String> incoming) {
        if (figureRefs == null || figureRefs.isEmpty()) {
            return incoming;
        }
        List<String> merged = new ArrayList<>(figureRefs);
        incoming.stream().filter(ref -> !merged.contains(ref)).forEach(merged::add);
        return merged;
    }

    public String text(BookLanguage language) {
        return language == BookLanguage.en ? textEn : textHi;
    }

    /** The address the founder spot-checks against the PDF (PLAN D14 ✅). */
    public String address() {
        return "ch " + chapterNo + " §" + section + " ¶" + paraNo;
    }

    public UUID getId() {
        return id;
    }

    public UUID getBookId() {
        return bookId;
    }

    public short getChapterNo() {
        return chapterNo;
    }

    public String getSection() {
        return section;
    }

    public short getParaNo() {
        return paraNo;
    }

    public UUID getNodeId() {
        return nodeId;
    }

    public String getTextEn() {
        return textEn;
    }

    public String getTextHi() {
        return textHi;
    }

    public List<String> getFigureRefs() {
        return figureRefs;
    }

    public boolean isHasEquations() {
        return hasEquations;
    }

    /** How this edition's text was read; null when that edition has not been loaded. */
    public ParagraphExtraction getExtraction(BookLanguage language) {
        return extraction.get(language);
    }

    public Map<BookLanguage, ParagraphExtraction> getExtraction() {
        return Map.copyOf(extraction);
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
