package com.margai.auth.internal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.net.InetAddress;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

/**
 * {@code otp_challenges} (TECH_PLAN §2.2 as amended at D7, migration V6): one row per code sent.
 * The row never holds the code — only {@code SHA-256(pepper ‖ id ‖ code)} — which is why the id
 * is assigned before the hash is computed rather than generated by the database
 * ({@link Persistable} tells Spring Data the row is new). {@code destination} is the E.164 phone
 * or the lowercased email the code went to; there is no foreign key to {@code users} because a
 * challenge precedes the account.
 */
@Entity
@Table(name = "otp_challenges")
public class OtpChallenge implements Persistable<UUID> {

    @Id
    private UUID id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 8)
    private OtpChannel channel;

    @Column(nullable = false, length = 254)
    private String destination;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private OtpPurpose purpose;

    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(nullable = false, length = 64)
    private String codeHash;

    @Column(nullable = false)
    private short attempts;

    @Column(nullable = false)
    private Instant expiresAt;

    private Instant verifiedAt;

    @JdbcTypeCode(SqlTypes.INET)
    private InetAddress requestIp;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    @Transient
    private boolean isNew = true;

    protected OtpChallenge() {
        // JPA
    }

    public OtpChallenge(UUID id, OtpChannel channel, String destination, OtpPurpose purpose, String codeHash,
            Instant expiresAt, InetAddress requestIp) {
        this.id = id;
        this.channel = channel;
        this.destination = destination;
        this.purpose = purpose;
        this.codeHash = codeHash;
        this.attempts = 0;
        this.expiresAt = expiresAt;
        this.requestIp = requestIp;
    }

    @PostPersist
    @PostLoad
    void markNotNew() {
        isNew = false;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @Override
    public UUID getId() {
        return id;
    }

    public OtpChannel getChannel() {
        return channel;
    }

    public String getDestination() {
        return destination;
    }

    public OtpPurpose getPurpose() {
        return purpose;
    }

    public String getCodeHash() {
        return codeHash;
    }

    public short getAttempts() {
        return attempts;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public Instant getVerifiedAt() {
        return verifiedAt;
    }

    public InetAddress getRequestIp() {
        return requestIp;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public boolean isVerified() {
        return verifiedAt != null;
    }

    public boolean isExpired(Instant now) {
        return !now.isBefore(expiresAt);
    }

    public boolean isExhausted(int maxAttempts) {
        return attempts >= maxAttempts;
    }

    /** Records one wrong code and returns the attempts used so far. */
    public short recordFailedAttempt() {
        attempts++;
        return attempts;
    }

    public void markVerified(Instant now) {
        this.verifiedAt = now;
    }
}
